language: android
android:
  components:
  - tools
  - build-tools-28.0.3
  - platform-tools
  - android-28
  - add-on
  - extra
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
script:
  - ./gradlew ktlint dependencies lint

notifications:
  slack: oslofjordencom:vImW8YpFDd6QNAO1lu9vW5WZ#android-ci
