language: android
android:
  components:
  - tools
  - build-tools-28.0.3
  - platform-tools
  - android-28
  - add-on
  - extra
script:
  - ./gradlew lint
  - ./gradlew :ktlint


notifications:
  slack: oslofjordencom:vImW8YpFDd6QNAO1lu9vW5WZ#android-ci
    on_success: always
    on_failure: always