package com.oslofjorden.oslofjordenturguide.MapView

enum class MarkerTypes {
    BEACH,TOILETT,PATHS,RESTAURANT,STORE,PARKING_TRANSPORT,POINT_OF_INTEREST,FISHING_SPOT,
    GUEST_HARBOR,OUT_HARBOR,PETROL_STATION,MARINA,RAMP,CRANE,LIGHTHOUSE,BOAT_STORE,CAMPING
}