# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do

  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

  lane :beta do

        gradle(task: 'clean')

        gradle(
          task: 'assemble',
          build_type: 'release',
        )
        supply(
          track: 'beta'
        )

        slack(message: 'Successfully distributed a new beta build')
      end

  lane :internal do

          gradle(task: 'clean')

          gradle(
            task: 'assemble',
            build_type: 'release',
          )
          supply(
            track: 'internal'
          )

          slack(message: 'Successfully distributed a new internal-tester build')
        end
end
